#!/usr/bin/env bash

set -euo pipefail

repo_root() {
    git rev-parse --show-toplevel
}

ROOT_DIR="$(repo_root)"
MINICONDA_DIR="${LSST_MINICONDA_DIR:-${ROOT_DIR}/miniconda3}"
ENVS_DIR="${LSST_ENVS_DIR:-${ROOT_DIR}/envs}"
VAR_DIR="${LSST_VAR_DIR:-${ROOT_DIR}/var}"
LSSTINSTALL_DIR="${LSST_LSSTINSTALL_DIR:-${ROOT_DIR}/var/lsstinstall}"
LSSTINSTALL="${LSSTINSTALL_DIR}/lsstinstall"
LSSTINSTALL_URL="${LSSTINSTALL_URL:-https://ls.st/lsstinstall}"
LSST_DOCS_URL="${LSST_DOCS_URL:-https://pipelines.lsst.io/install/lsstinstall.html}"
LSST_TAGS_URL="${LSST_TAGS_URL:-https://eups.lsst.codes/stack/src/tags/}"
LSST_PACKAGE="${LSST_PACKAGE:-lsst_distrib}"
MINICONDA_INSTALLER_URL="${MINICONDA_INSTALLER_URL:-}"

log() {
    printf '==> %s\n' "$*"
}

fetch() {
    curl -fsSL "$1"
}

resolve_current_stable_tag() {
    if [[ -n "${LSST_STACK_TAG:-}" ]]; then
        printf '%s\n' "${LSST_STACK_TAG}"
        return
    fi

    local tag
    tag="$({ fetch "${LSST_TAGS_URL}" || true; } \
        | sed -nE 's/.*href="(v[0-9]+_[0-9]+(_[0-9]+)?\.list)".*/\1/p' \
        | sed 's/\.list$//' \
        | sort -V \
        | tail -n 1)"
    if [[ -n "${tag}" ]]; then
        printf '%s\n' "${tag}"
        return
    fi

    tag="$({ fetch "${LSST_DOCS_URL}" || true; } \
        | sed -nE 's/.*current official release version, `?(v[0-9]+_[0-9]+(_[0-9]+)?).*/\1/p' \
        | head -n 1)"
    if [[ -n "${tag}" ]]; then
        printf '%s\n' "${tag}"
        return
    fi

    printf 'Could not resolve current stable LSST tag. Set LSST_STACK_TAG explicitly.\n' >&2
    return 1
}

env_name_for_tag() {
    local tag="$1"
    printf 'lsst_%s\n' "${tag#v}"
}

write_current_env_file() {
    local tag="$1"
    local env_name="$2"
    mkdir -p "${VAR_DIR}"
    cat > "${VAR_DIR}/current-env.sh" <<EOF_CURRENT
# Generated by scripts/setup.sh or scripts/update.sh.
export LSST_STACK_TAG="${tag}"
export LSST_CONDA_ENV_NAME="${env_name}"
export LSST_ENV_PREFIX="${ENVS_DIR}/${env_name}"
export LSST_LOAD_SCRIPT="${ROOT_DIR}/loadLSST.sh"
EOF_CURRENT
}

read_current_env_file() {
    # shellcheck disable=SC1091
    source "${VAR_DIR}/current-env.sh"
}

ensure_lsstinstall() {
    mkdir -p "${LSSTINSTALL_DIR}"
    if [[ ! -x "${LSSTINSTALL}" ]]; then
        log "Downloading lsstinstall from ${LSSTINSTALL_URL}"
        fetch "${LSSTINSTALL_URL}" > "${LSSTINSTALL}"
        chmod u+x "${LSSTINSTALL}"
    fi
}

miniconda_installer_url() {
    if [[ -n "${MINICONDA_INSTALLER_URL}" ]]; then
        printf '%s\n' "${MINICONDA_INSTALLER_URL}"
        return
    fi

    local system machine platform
    system="$(uname -s)"
    machine="$(uname -m)"
    case "${system}:${machine}" in
        Linux:x86_64) platform="Linux-x86_64" ;;
        Linux:aarch64) platform="Linux-aarch64" ;;
        Darwin:x86_64) platform="MacOSX-x86_64" ;;
        Darwin:arm64) platform="MacOSX-arm64" ;;
        *)
            printf 'Unsupported platform for Miniconda bootstrap: %s %s\n' "${system}" "${machine}" >&2
            return 1
            ;;
    esac

    printf 'https://repo.anaconda.com/miniconda/Miniconda3-latest-%s.sh\n' "${platform}"
}

install_miniconda() {
    if [[ -x "${MINICONDA_DIR}/bin/conda" ]]; then
        return
    fi

    local installer
    installer="${VAR_DIR}/miniconda.sh"
    mkdir -p "${VAR_DIR}"
    log "Downloading Miniconda installer"
    fetch "$(miniconda_installer_url)" > "${installer}"
    log "Installing Miniconda at ${MINICONDA_DIR}"
    bash "${installer}" -b -p "${MINICONDA_DIR}"
}

configure_local_conda_envs_dir() {
    mkdir -p "${ENVS_DIR}"
    "${MINICONDA_DIR}/bin/conda" config --system --prepend envs_dirs "${ENVS_DIR}"
    "${MINICONDA_DIR}/bin/conda" config --system --set auto_activate_base false
}
