#!/usr/bin/env bash

set -euo pipefail

repo_root() {
    git rev-parse --show-toplevel
}

ROOT_DIR="$(repo_root)"
MINICONDA_DIR="${LSST_MINICONDA_DIR:-${ROOT_DIR}/miniconda3}"
ENVS_DIR="${LSST_ENVS_DIR:-${ROOT_DIR}/envs}"
VAR_DIR="${LSST_VAR_DIR:-${ROOT_DIR}/var}"
LSSTINSTALL_DIR="${LSST_LSSTINSTALL_DIR:-${ROOT_DIR}/var/lsstinstall}"
LSSTINSTALL="${LSSTINSTALL_DIR}/lsstinstall"
LSSTINSTALL_URL="${LSSTINSTALL_URL:-https://ls.st/lsstinstall}"
LSST_STACK_TAG_DEFAULT="v29_2_1"
RUBIN_ENV_VERSION="${LSST_RUBIN_ENV_VERSION:-10.1.0}"
LSST_PACKAGE="${LSST_PACKAGE:-lsst_distrib}"
MINICONDA_INSTALLER_URL="${MINICONDA_INSTALLER_URL:-}"

log() {
    printf '==> %s\n' "$*"
}

fetch() {
    curl -fsSL "$1"
}

current_stable_tag() {
    printf '%s\n' "${LSST_STACK_TAG:-${LSST_STACK_TAG_DEFAULT}}"
}

env_name_for_tag() {
    local tag="$1"
    printf 'lsst_%s\n' "${tag#v}"
}

env_prefix_for_name() {
    local env_name="$1"
    printf '%s/%s\n' "${ENVS_DIR}" "${env_name}"
}

write_current_env_file() {
    local tag="$1"
    local env_name="$2"
    local env_prefix
    env_prefix="$(env_prefix_for_name "${env_name}")"
    mkdir -p "${VAR_DIR}"
    cat > "${VAR_DIR}/current-env.sh" <<EOF_CURRENT
# Generated by scripts/setup.sh or scripts/update.sh.
export LSST_STACK_TAG="${tag}"
export LSST_CONDA_ENV_NAME="${env_name}"
export LSST_ENV_PREFIX="${env_prefix}"
export LSST_LOAD_SCRIPT="${ROOT_DIR}/loadLSST.sh"
EOF_CURRENT
}

read_current_env_file() {
    # shellcheck disable=SC1091
    source "${VAR_DIR}/current-env.sh"
}

ensure_lsstinstall() {
    mkdir -p "${LSSTINSTALL_DIR}"
    if [[ ! -x "${LSSTINSTALL}" ]]; then
        log "Downloading lsstinstall from ${LSSTINSTALL_URL}"
        fetch "${LSSTINSTALL_URL}" > "${LSSTINSTALL}"
        chmod u+x "${LSSTINSTALL}"
    fi
}

miniconda_installer_url() {
    if [[ -n "${MINICONDA_INSTALLER_URL}" ]]; then
        printf '%s\n' "${MINICONDA_INSTALLER_URL}"
        return
    fi

    local system machine platform
    system="$(uname -s)"
    machine="$(uname -m)"
    case "${system}:${machine}" in
        Linux:x86_64) platform="Linux-x86_64" ;;
        Linux:aarch64) platform="Linux-aarch64" ;;
        Darwin:x86_64) platform="MacOSX-x86_64" ;;
        Darwin:arm64) platform="MacOSX-arm64" ;;
        *)
            printf 'Unsupported platform for Miniconda bootstrap: %s %s\n' "${system}" "${machine}" >&2
            return 1
            ;;
    esac

    printf 'https://repo.anaconda.com/miniconda/Miniconda3-latest-%s.sh\n' "${platform}"
}

install_miniconda() {
    if [[ -x "${MINICONDA_DIR}/bin/conda" ]]; then
        return
    fi

    local installer
    installer="${VAR_DIR}/miniconda.sh"
    mkdir -p "${VAR_DIR}"
    log "Downloading Miniconda installer"
    fetch "$(miniconda_installer_url)" > "${installer}"
    log "Installing Miniconda at ${MINICONDA_DIR}"
    bash "${installer}" -b -p "${MINICONDA_DIR}"
}

configure_local_conda_envs_dir() {
    mkdir -p "${ENVS_DIR}"
    "${MINICONDA_DIR}/bin/conda" config --system --prepend envs_dirs "${ENVS_DIR}"
    "${MINICONDA_DIR}/bin/conda" config --system --set auto_activate_base false
}

activate_conda() {
    # shellcheck disable=SC1091
    source "${MINICONDA_DIR}/etc/profile.d/conda.sh"
}

ensure_lsst_conda_env() {
    local env_name="$1"
    local env_prefix
    env_prefix="$(env_prefix_for_name "${env_name}")"

    if [[ -d "${env_prefix}/conda-meta" ]]; then
        return
    fi

    log "Creating conda environment ${env_name} at ${env_prefix}"
    "${MINICONDA_DIR}/bin/conda" create -y --prefix "${env_prefix}" -c conda-forge "rubin-env=${RUBIN_ENV_VERSION}"
}

activate_lsst_conda_env() {
    local env_name="$1"

    activate_conda
    conda activate "${env_name}"
}

run_lsstinstall_for_env() {
    local tag="$1"
    local env_name="$2"

    export LSST_CONDA_ENV_NAME="${env_name}"
    activate_lsst_conda_env "${env_name}"
    "${LSSTINSTALL}" -p "${MINICONDA_DIR}" -T "${tag}" -e "${env_name}"
}

source_lsst_env() {
    local env_name="$1"

    export LSST_CONDA_ENV_NAME="${env_name}"
    # shellcheck disable=SC1091
    source "${ROOT_DIR}/loadLSST.sh"
}
